### PR TITLE
Hi OpenDDR-org

### PR DESCRIPTION
**Pull request by robrohan**
I am an engineer working for VirtualTourist.com, and we've been looking at using OpenDDR in one of our applications.  We are currently using Grails and Maven.

We're still evaluating if we're going to use OpenDDR, but we thought we'd kick back upstream some of the changes we made while playing around with it.  We added:
- A maven layout and build script (the pom.xml - I would guess apache would like this :D)
- Added code to put the oddr.properties file and the xml files in the created jar
- ... and then updated the code to load the XML files from the jar (instead of the full file system path).  The full path way still works if the path starts with a "/" - see FileLocator and the changes in ODDRService and ODDRVocabularyService
- Added DeviceService so that you can load the code with spring dependency injection - this is a big thing in Grails because it makes it a "normal" service.

Thanks for working on this - I hope we wind up using it.   If you do accept the changes, please credit VirtualTourist.com (I made the modifications if you have any questions, but I did it on their dime and it would be cool if they got the credit)

Cheers,
rob

### CODE REVIEW

**Comment by samspycher** [comment]
Hi Rob, OpenDDR devs,

Thanks Rob, I will be using/adapting this happily! 

Is there a reason for this not being added to the githup repo?

Cheers,
Sam

**Comment by robrohan** [comment]
Hi Sam,  not that I can think of.  It should be backwards compatible (though I did not specifically test for that)

Cheers

**Comment by tomcjohn** [comment]
Bump.

Any plans to merge this maven integration stuff into OpenDDRdotORG:master soon?

Thanks,
Tom

**Comment by OpenDDR** [comment]
This is pretty much applied since DeviceMap

**Pull request closed without merging**
